### PR TITLE
Fixup - use 2 space indents

### PR DESCRIPTION
**Pull request by Mehuge**
as per CU coding standards

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/CUModSquad/cu-events/pull/5" target="_blank">ReviewNinja

**Comment by saddieeiddas** [comment]
this should all be done in #3 . not sure if this will clash with that

**Comment by saddieeiddas** [comment]
@mehuge can close this I think

**Comment by Mehuge** [comment]
Yep, you are right, closing

**Pull request closed without merging**
